name: Run Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Lighthouse on urls and validate with lighthouserc
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: 'https://michaelfromyeg.github.io/gha-aws-deploy-feature-branch/'
          configPath: '.github/workflows/lighthouserc.json'